# Generated by Django 5.1.4 on 2025-01-09 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
    ]
